export const amplitudeEvents = {
  appLoad: "App Load",
  logInSuccessful: "Log In Successful",
  logOutSuccessful: "Log Out Successful",
  About: "About Screen",
  ArticleScreen: "Article",
  ArticleIndex: "Article Index",
  ContactUs: "Contact Us",
  Explore: "Explore",
  Group: "Group",
  HomeLoggedIn: "Home Logged In",
  Info: "Info",
  Login: "Login",
  LogoutConfirmation: "Logout Confirmation",
  Password: "Password",
  ResetCounter: "Reset Counter",
  Resources: "Resources",
  Schedule: "Schedule",
  Services: "Services",
  Settings: "Settings",
  SoberStartDate: "Sober Start Date",
  Stats: "Stats",
  SuccessStories: "Success Stories",
  Terms: "Terms",
  WelcomeOnboarding: "Welcome Onboarding",
  WelcomeOnboarding2: "Welcome Onboarding 2",
};
