import { Logo } from "./components/atoms";

export const screens = {
  home: { name: "Home", title: "Home" },
  homeNavigation: { name: "HomeNavigation", title: "Home" },
  contact: { name: "Contact", title: "Contact" },
  about: { name: "About Us", title: "About" },
  services: { name: "Services", title: "Services" },
  notFound: { name: "NotFound", title: "Not Found" },
  info: { name: "Info", title: "Info" },
  group: { name: "Group", title: "Group" },
  resources: { name: "Resources", title: "Resources" },
  terms: { name: "Terms of service", title: "Terms of Service" },
  login: { name: "Login", title: <Logo /> },
  homeLoggedIn: { name: "Home", title: "Home LoggedIn" },
  explore: { name: "Explore", title: "Explore" },
  settings: { name: "Settings", title: "Settings" },
  logoutConfirmation: { name: "Log out", title: "Log out" },
  liveStream: { name: "LiveStream", title: "Live Stream" },
  schedule: { name: "Schedule", title: "Schedule" },
  articleIndex: { name: "ArticleIndex", title: "Articles" },
  article: { name: "Article" },
  welcome: { name: "WelcomeOnboarding", title: "WelcomeOnboarding" },
  secondWelcome: { name: "WelcomeOnboarding2", title: "WelcomeOnboarding2" },
  stats: { name: "Stats", title: "Stats" },
  resetCounter: { name: "Set Sober Start Date", title: "Reset Counter" },
  soberStartDate: { name: "SoberStartDate", title: "Sober Start Date" },
  successStories: { name: "SuccessStories", title: "Success Stories" },
  successStory: { name: "SuccessStory", title: "Success Story" },
  password: { name: "Password", title: "Password" },
};
